version: "3.9"
services:
  postgres1:
    image: postgres:14.5
    shm_size: 128mb
    env_file:
      - ./docker/db/config/library.env
    volumes:
      - ./docker/db/scripts/library/:/docker-entrypoint-initdb.d/
      - ./dz/postgres1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
